# Generated by Django 3.2.25 on 2024-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_timelog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLog',
            new_name='TimeLogs',
        ),
    ]
