# Generated by Django 3.2.25 on 2024-05-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_timelog_timelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='time_logs/')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.tablestudents')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeLogs',
        ),
    ]
