# Generated by Django 3.2.25 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='announcement/')),
                ('Description', models.CharField(max_length=150)),
                ('Status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=30)),
            ],
        ),
    ]
