# Generated by Django 3.2.25 on 2024-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='announcement/')),
                ('Description', models.CharField(max_length=150)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
