# Generated by Django 4.2.14 on 2024-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240712_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='announcement/')),
                ('Category', models.CharField(blank=True, max_length=150, null=True)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=450)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnouncementTable',
        ),
    ]
